config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope :acd, :path => '/acd' do
    resources :ansible_playbooks, :controller => 'foreman_acd/ansible_playbooks' do
      collection do
        get 'auto_complete_search'
        put 'sync_git_repo'
        post 'sync_git_repo'
      end

      member do
        post 'sync_git_repo'
        get 'import_vars'
      end
    end
    resources :app_definitions, :controller => 'foreman_acd/app_definitions' do
      collection do
        get 'auto_complete_search'
        get 'import'
        post 'handle_file_upload'
      end

      member do
        get 'export'
      end
    end

    resources :app_instances, :controller => 'foreman_acd/app_instances' do
      collection do
        get 'auto_complete_search'
      end

      member do
        post 'deploy'
        get 'report'
        delete 'destroy_with_hosts'
      end
    end

    match '/remote_execution', :controller => 'foreman_acd/remote_execution', :action => 'create', :via => [:post]

    get 'ui_acd_app/:id', :to => 'ui_acd#app', :constraints => { :id => /[\w.-]+/ }, :as => :ui_acd_app
    get 'ui_acd_foreman_data/:id', :to => 'ui_acd#foreman_data', :constraints => { :id => /[\w.-]+/ }, :as => :ui_acd_foreman_data
    get 'ui_acd_ansible_data/:id', :to => 'ui_acd#ansible_data', :constraints => { :id => /[\w.-]+/ }, :as => :ui_acd_ansible_data
    get 'ui_acd_report_data/:id', :to => 'ui_acd#report_data', :constraints => { :id => /[\w.-]+/ }, :as => :ui_acd_report_data
    get 'ui_acd_validate_hostname', :to => 'ui_acd#validate_hostname', :as => :ui_acd_validate_hostname

    scope :api, :path => '/api', :defaults => { :format => 'json' } do
      scope '(:apiv)', :defaults => { :apiv => 'v2' },
                       :apiv => /v1|v2/, :constraints => ApiConstraints.new(:version => 2) do
        constraints(:id => /[\w.-]+/) do
          resources :app_definitions, :only => [:show, :index], :controller => 'foreman_acd/api/v2/app_definitions', :as => :acd_api_v2_app_definitions
          resources :app_instances, :only => [:show, :index], :controller => 'foreman_acd/api/v2/app_instances', :as => :api_v2_foreman_acd_app_instances
          resources :ansible_playbooks, :only => [:show, :index], :controller => 'foreman_acd/api/v2/ansible_playbooks', :as => :api_v2_foreman_acd_ansible_playbooks do
            member do
              get 'grab'
            end
          end
        end
      end
    end
  end
end

app/models/foreman_acd/app_instance.rb
# frozen_string_literal: true

module ForemanAcd
  # Application Instance
  class AppInstance < ApplicationRecord
    include Authorizable
    include ForemanTasks::Concerns::ActionSubject
    extend FriendlyId
    friendly_id :name
    include Parameterizable::ByIdName

    self.table_name = 'acd_app_instances'
    belongs_to :last_deploy_task, :class_name => 'ForemanTasks::Task'
    belongs_to :initial_configure_task, :class_name => 'ForemanTasks::Task'
    validates :name, :presence => true, :uniqueness => true
    validates :app_definition, :presence => true
    belongs_to :app_definition, :inverse_of => :app_instances
    belongs_to :organization
    validates :organization, :presence => true
    belongs_to :location
    validates :location, :presence => true
    has_many :foreman_hosts, :inverse_of => :app_instance, :dependent => :destroy
    scoped_search :on => :name
    default_scope -> { order('acd_app_instances.name') }
    attr_accessor :hosts

    def self.humanize_class_name(_name = nil)
      _('App Instance')
    end

    def self.permission_name
      'app_instances'
    end

    def clean_all_hosts
      remember_host_ids = foreman_hosts.select(&:fresh_host?).map(&:host_id)

      # Clean the app instance association first
      foreman_hosts.update_all(:host_id => nil)

      # Remove all hosts afterwards
      delete_hosts(remember_host_ids)
    end

    def clean_hosts_by_id(ids = [])
      # Clean the app instance association first
      foreman_hosts.where(:host_id => ids, :is_existing_host => false).update_all(:host_id => nil)

      # Remove all hosts afterwards
      delete_hosts(ids)
    end

    def hosts_deployment_finished?
      return true if all_hosts_deployed?

      ::Foreman::Logging.logger('foreman_acd').info('Another host is still in build-phase. Wait for it...')
      false
    end

    def deployment_state
      return :new if last_deploy_task.nil?
      return :initiated if !last_deploy_task.nil? && last_deploy_task.ended_at.nil?

      if all_hosts_deployed?
        :finished
      elsif last_deploy_task.ended_at? && last_deploy_task.result != 'success'
        :failed
      else
        :pending
      end
    end

    def initial_configure_job
      return nil if initial_configure_task.nil?
      return JobInvocation.find(initial_configure_task.output['configure_job_id']) if initial_configure_task.output.key?('configure_job_id') &&
                                                                                      !initial_configure_task.output['configure_job_id'].nil?
      nil
    end

    def initial_configure_state
      return :unconfigured if initial_configure_job.nil? && initial_configure_task.nil?
      return :scheduled if initial_configure_job.nil?
      return :pending unless initial_configure_job.finished?
      initial_configure_job.status_label.to_sym
    end

    private

    def all_hosts_deployed?
      foreman_hosts.each do |foreman_host|
        return false if foreman_host.host.nil? || foreman_host.host.build?
      end
      true
    end

    def delete_hosts(ids = [])
      return if ids.empty?
      ids.each do |host_id|
        h = ::Host.find(host_id) unless host_id.nil?
        if h
          Katello::RegistrationManager.unregister_host(h, :unregistering => false) if ForemanAcd.with_katello?
          h.destroy
        end
      end
    end
  end
end

app/controllers/foreman_acd/ansible_playbooks_controller.rb
# frozen_string_literal: true

module ForemanAcd
  # Ansible Playbook Controller
  class AnsiblePlaybooksController < ::ForemanAcd::ApplicationController
    include Foreman::Controller::AutoCompleteSearch
    include ::ForemanAcd::Concerns::AnsiblePlaybookParameters

    before_action :find_resource, :only => [:edit, :update, :destroy, :import_vars]
    after_action :delete_synced_repo, :only => [:new, :edit, :create, :update, :destroy, :index]

    def index
      @ansible_playbooks = resource_base.search_for(params[:search], :order => params[:order]).paginate(:page => params[:page])
    end

    def new
      @ansible_playbook = AnsiblePlaybook.new
    end

    def create
      @ansible_playbook = AnsiblePlaybook.new(ansible_playbook_params)
      if session[:git_path]
        @ansible_playbook.update(:path => ansible_playbook_full_path(ansible_playbook_rename(@ansible_playbook[:name])))
        FileUtils.mv(session[:git_path], @ansible_playbook[:path])
        session[:git_path] = nil
      end
      if @ansible_playbook.save
        process_success :success_msg => _("Successfully created %s. You need to press the \"Import groups\" button
                                           before this ansible playbook can be used in App Definitions!") % @ansible_playbook
      else
        process_error
      end
    end

    def edit
    end

    def update
      # Move synced repo to new path if ansible_playbook name is changed
      if !session[:git_path].nil? && ansible_playbook_params[:name] != @ansible_playbook[:name]
        FileUtils.mv(@ansible_playbook[:path], ansible_playbook_full_path(ansible_playbook_rename(ansible_playbook_params[:name])))
        @ansible_playbook.update(:path => ansible_playbook_full_path(ansible_playbook_rename(ansible_playbook_params[:name])))
        session[:git_path] = nil

      # Remove old version and copy new version of synced repository
      elsif !session[:git_path].nil? && ansible_playbook_params[:name] == @ansible_playbook.name
        remove_ansible_dir(@ansible_playbook[:path]) if @ansible_playbook.path
        @ansible_playbook.update(:path => ansible_playbook_full_path(ansible_playbook_rename(@ansible_playbook[:name])))
        FileUtils.mv(session[:git_path], @ansible_playbook[:path])
        session[:git_path] = nil
      end

      if @ansible_playbook.update(ansible_playbook_params)
        process_success
      else
        process_error
      end
    end

    def destroy
      if @ansible_playbook.destroy
        process_success
      else
        process_error
      end
    end

    def sync_git_repo
      @ansible_playbook = AnsiblePlaybook.new
      sync_params = params[:ansible_playbook]
      dir = Dir.mktmpdir

      begin
        git = Git.init(dir)

        if ForemanAcd.proxy_setting.present?
          git.config('http.proxy', ForemanAcd.proxy_setting)
          logger.info("HTTP Proxy used: #{git.config['http.proxy']}")
        end

        if sync_params[:git_commit].empty?
          if ForemanAcd.proxy_setting.present?
            err_msg = _('Please set the Git Branch/Tag/Commit. This setting is necessary if a HTTP proxy is used!')
            raise StandardError, err_msg
          else
            commit = Git.ls_remote(sync_params[:git_url])['head'][:sha]
          end
        else
          commit = sync_params[:git_commit]
        end

        git.add_remote('origin', sync_params[:git_url])
        git.fetch
        git.checkout(commit)

        session[:git_path] = git.dir.path
      rescue StandardError => e
        logger.error("Failed to sync git repository: #{e}")
        render :json => { :status => 'error', :message => e }, :status => :internal_server_error
      end
    end

    # Remove abandoned synced git repositories
    def delete_synced_repo
      names = []
      AnsiblePlaybook.all.each do |ansible_playbook|
        names.push(ansible_playbook_rename(ansible_playbook.name))
      end
      names.push('.', '..')
      return unless Dir.exist?(ForemanAcd.ansible_playbook_path)
      Dir.foreach(ForemanAcd.ansible_playbook_path) do |dirname|
        next if names.include? dirname
        remove_ansible_dir(ansible_playbook_full_path(dirname))
        logger.info("Successfully removed #{dirname}")
      end
    end

    def action_permission
      case params[:action]
      when 'import_vars'
        :import_vars
      when 'sync_git_repo'
        :sync_git_repo
      when 'grab'
        :grab
      else
        super
      end
    end

    # We need to move these to a smart_proxy_acd
    def extract_variables(playbook_path)
      errors = []
      vars = {}

      unless File.directory?(playbook_path) || File.directory?("#{playbook_path}/group_vars")
        errors << "Playbook path '#{playbook_path}' or '#{playbook_path}/group_vars' doesn't exist"
        return vars, errors
      end

      everything_empty = true

      vars_files = Dir.glob("#{playbook_path}/group_vars/**/*")
      vars_files.each do |vars_file|
        loaded_yaml = {}
        next if File.directory?(vars_file)

        begin
          loaded_yaml = YAML.load_file(vars_file)
        rescue Psych::SyntaxError
          err = "#{vars_file} is not YAML file"
          logger.error(err)
          errors << err
        end
        unless loaded_yaml.is_a? Hash
          err = "Could not parse YAML file #{vars_file}"
          logger.error(err)
          errors << err
        end
        everything_empty = false unless loaded_yaml.empty?

        # We need to support: group_vars/group_file and group_vars/group_dir/yaml_files
        dir_and_file = File.split(vars_file)

        group_name = if File.basename(dir_and_file[0]) == 'group_vars' # in case of group_vars/group_file
                       File.basename(dir_and_file[1], '.*')
                     else # in case of group_vars/group_dir/yaml_files
                       File.basename(dir_and_file[0])
                     end

        logger.debug("Add ansible vars from file #{vars_file} to group #{group_name}")

        if vars.key?(group_name)
          vars[group_name].merge!(loaded_yaml)
        else
          vars[group_name] = loaded_yaml
        end
      end

      errors << "No ansible group variable in #{playbook_path} defined." if everything_empty

      [vars, errors]
    end

    def import_vars
      logger.debug("Load ansible group vars for #{@ansible_playbook} from #{@ansible_playbook.path}")
      vars, errors = extract_variables(@ansible_playbook.path)
      @ansible_playbook.vars = vars.to_json
      @ansible_playbook.save
      if errors.empty?
        process_success :success_msg => _('Successfully loaded ansible group variables from %s') % @ansible_playbook.name, :redirect => ansible_playbooks_path
      else
        process_error :error_msg => _(errors.join(' ')), :redirect => ansible_playbooks_path
      end
    end

    private

    def ansible_playbook_rename(name)
      name.split(/\W+/).join('_')
    end

    def remove_ansible_dir(dirpath)
      unless dirpath.start_with? ForemanAcd.ansible_playbook_path
        logger.error("Sorry, the directory #{dirpath} is not within #{ForemanAcd.ansible_playbook_path} and will therefore not be cleaned up!")
        return false
      end
      FileUtils.rm_rf(dirpath) if Dir.exist?(dirpath)
    end

    def ansible_playbook_full_path(dirname)
      File.join(ForemanAcd.ansible_playbook_path, dirname)
    end
  end
end

app/controllers/foreman_acd/api/v2/ansible_playbooks_controller.rb
# frozen_string_literal: true

module ForemanAcd
  module Api
    module V2
      # API controller for Ansible Playbooks
      class AnsiblePlaybooksController < ::ForemanAcd::Api::V2::BaseController
        include ::Foreman::Controller::SmartProxyAuth
        include ::ForemanAcd::Concerns::AnsiblePlaybookParameters

        before_action :find_resource, :except => [:index, :create, :grab]

        add_smart_proxy_filters :grab, :features => 'ACD'

        api :GET, '/ansible_playbooks/:id', N_('Show ansible playbook')
        param :id, :identifier, :required => true
        def show
        end

        api :GET, '/ansible_playbooks', N_('List ansible playbooks')
        param_group :search_and_pagination, ::Api::V2::BaseController
        add_scoped_search_description_for(AnsiblePlaybook)
        def index
          @ansible_playbooks = resource_scope_for_index
        end

        def_param_group :ansible_playbook do
          param :ansible_playbook, Hash, :required => true, :action_aware => true do
            param :name, String, :required => true
            param_group :taxonomies, ::Api::V2::BaseController
            param :description, String, :required => true
            param :services, String, :required => true
          end
        end

        api :POST, '/ansible_playbooks', N_('Create a ansible playbook')
        param_group :ansible_playbook, :as => :create
        def create
          @ansible_playbook = AnsiblePlaybook.new(ansible_playbook_params)
          process_response @ansible_playbook.save
        end

        api :DELETE, '/ansible_playbooks/:id', N_('Deletes ansible playbook')
        param :id, :identifier, :required => true
        def destroy
          process_response @ansible_playbook.destroy
        end

        api :GET, '/ansible_playbooks/:id/grab', N_('Grab ansible playbook')
        param :id, :identifier, :required => true
        def grab
          ap = resource_class.find(params['id'])
          command = "tar cz -C #{ap.path} --exclude \".git\" . 2>/dev/null | base64"
          result = `#{command}`
          send_data result, :type => 'text/plain', :disposition => 'inline'
        end

        def action_permission
          case params[:action]
          when 'grab'
            'grab'
          else
            super
          end
        end

        def resource_class
          ForemanAcd::AnsiblePlaybook
        end
      end
    end
  end
end

app/controllers/foreman_acd/api/v2/app_definitions_controller.rb
# frozen_string_literal: true

module ForemanAcd
  module Api
    module V2
      # API controller for App Definitions
      class AppDefinitionsController < ::ForemanAcd::Api::V2::BaseController
        include ::ForemanAcd::Concerns::AppDefinitionParameters

        before_action :find_resource, :except => [:index, :create]

        api :GET, '/app_definitions/:id', N_('Show application definition')
        param :id, :identifier, :required => true
        def show
        end

        api :GET, '/app_definitions', N_('List application definitions')
        param_group :search_and_pagination, ::Api::V2::BaseController
        add_scoped_search_description_for(AppDefinition)
        def index
          @app_definitions = resource_scope_for_index
        end

        def_param_group :app_definition do
          param :app_definition, Hash, :required => true, :action_aware => true do
            param :name, String, :required => true
            param_group :taxonomies, ::Api::V2::BaseController
            param :description, String, :required => true
            param :services, String, :required => true
          end
        end

        api :POST, '/app_definitions', N_('Create a application definition')
        param_group :app_definition, :as => :create
        def create
          @app_definition = AppDefinition.new(app_definition_params)
          process_response @app_definition.save
        end

        api :DELETE, '/app_definitions/:id', N_('Deletes application definition')
        param :id, :identifier, :required => true
        def destroy
          process_response @app_definition.destroy
        end

        def controller_permission
          'app_definitions'
        end

        def resource_class
          ForemanAcd::AppDefinition
        end
      end
    end
  end
end

app/views/foreman_acd/app_instances/_form.html.erb
<%
    if @app_instance.new_record?
      json = {
        "mode": "newInstance",
        "organization": current_organization,
        "location": current_location,
        "applications": @applications,
        "appDefinitionUrl": ui_acd_app_path("__id__"),
        "foremanDataUrl": ui_acd_foreman_data_path("__id__"),
        "ansibleVarsAll": [],
      }
    else
      json = {
        "mode": "editInstance",
        "organization": current_organization,
        "location": current_location,
        "appDefinitionUrl": ui_acd_app_path("__id__"),
        "foremanDataUrl": ui_acd_foreman_data_path("__id__"),
        "appDefinition": {
          "id": @app_instance.app_definition.id,
          "name": @app_instance.app_definition.name,
        },
        "hosts": collect_hosts_data,
        "ansibleVarsAll": @app_instance.ansible_vars_all.blank? ? [] : JSON.parse(@app_instance.ansible_vars_all),
      }
    end

    json["supportedPlugins"] = {}
    json["supportedPlugins"]["puppet"] = defined?(ForemanPuppet) != nil
    json["supportedPlugins"]["katello"] = defined?(Katello) != nil
%>

<%= form_for @app_instance, :url => (@app_instance.new_record? ? app_instances_path : app_instance_path(:id => @app_instance.id)) do |f| %>
  <%= base_errors_for @app_instance %>
  <ul class="nav nav-tabs" data-tabs="tabs">
    <li class="active"><a href="#primary" data-toggle="tab"><%= _('Application Instances') %></a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="primary">
      <%= text_f f, :name %>
      <%= text_f f, :description %>

      <div id='app_instance'></div>
        <%=  react_component('ApplicationInstance', :data => json) %>
      </div>
    </div>
  </div>
  <%= f.hidden_field :organization_id %>
  <%= f.hidden_field :location_id %>
  <%= submit_or_cancel f %>
<% end %>

app/views/foreman_acd/app_instances/edit.html.erb
<%=
  breadcrumbs(:resource_url => "/acd/api/v2/app_instances?location_id=#{@location.id}&organization_id=#{@organization.id}",
              :items => [
                { :caption => _('App Instances'),
                  :url => url_for(app_instances_path) },
                { :caption => "Edit #{@app_instance.name}",
                  :url => (edit_app_instance_path(@app_instance) if authorized_for(hash_for_edit_app_instance_path(@app_instance))) }
              ])
%>

<% title(_('Edit Application Instance %s') % @app_instance) %>

<% content_for(:javascripts) do %>
  <%= webpacked_plugins_js_for :foreman_acd %>
<% end %>

<%= render :partial => 'form' %>

app/views/foreman_acd/app_instances/index.html.erb
<% title _('Application Instances') %>

<% title_actions button_group(new_link(_('New Application Instance'))) %>

<table class="table table-bordered table-striped">
  <tr>
    <th><%= sort :name, :as => s_('AppInstance|Name') %></th>
    <th><%= sort :application, :as => _('Application'), :default => 'DESC' %></th>
    <th><%= _('Description') %></th>
    <th><%= _('Report') %></th>
    <th></th>
  </tr>
  <% for app_instance in @app_instances %>
    <tr>
      <td><%=link_to_if_authorized h(app_instance.name), hash_for_edit_app_instance_path(:id => app_instance) %></td>
      <td><%= app_instance.app_definition %></td>
      <td><%= app_instance.description %></td>
      <td><%= link_to_if((authorized_for(:auth_object => app_instance, :authorizer => authorizer, :permission => :report_app_instances) &&
                         !app_instance.last_deploy_task.nil? && app_instance.last_deploy_task.ended_at?),
                         _("Show Report"),
                         hash_for_report_app_instance_path(:id => app_instance),
                         :method => :get, :title => _("Show last deployment report for application #{app_instance}")) %></td>
      <td>
        <%= action_buttons(
          display_link_if_authorized(_("Deploy"), { :use_route => :app_instances,
                                                    :id => app_instance.id,
                                                    :action => :deploy,
                                                    :auth_object => app_instance,
                                                    :controller => :app_instances },
                                                    {
                                                      :remote => false,
                                                      :href => "#", # don't navigate
                                                      :data => {
                                                        :toggle => "modal",
                                                        :target => "#deploy#{app_instance.id}"
                                                      },
                                                      :title => _("Deploy application #{app_instance}")
                                                    }),
          display_link_if_authorized(_("Run Playbook"),
                                     hash_for_remote_execution_path(:id => app_instance.id),
                                     :method => :post,
                                     :title => _("Run ansible playbook for application #{app_instance}")),
          display_link_if_authorized(_("Run Playbook - customize first"),
                                     hash_for_remote_execution_path(:id => app_instance.id, :customize => true),
                                     :method => :post,
                                     :title => _("Prepare job to run ansible playbook for application #{app_instance}")),
          display_link_if_authorized(_("Delete"), { :use_route => :app_instances,
                                                    :id => app_instance.id,
                                                    :action => :destroy,
                                                    :auth_object => app_instance,
                                                    :controller => :app_instances },
                                                    {
                                                      :remote => false,
                                                      :href => "#", # don't navigate
                                                      :data => {
                                                        :toggle => "modal",
                                                        :target => "#delete#{app_instance.id}"
                                                      },
                                                      :title => _("Delete application #{app_instance}")
                                                    })
          ) %>
    </td>
    </tr>
    <!-- Delete Modal -->
      <div class="modal fade" id="delete<%=app_instance.id%>" tabindex="-1" role="dialog" aria-labelledby="deleteLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title"><%= _('Confirmation')%></h4>
            </div>
            <div class="modal-body">
              <p> <%= _("Confirm to delete application instance: ") %> <%= app_instance %></p>
              <%= form_tag destroy_with_hosts_app_instance_path(:id => app_instance.id), :method => :delete do %>
                <% showSelectHostsNote = true %>
                <% app_instance.foreman_hosts.select(&:fresh_host?).each do |foreman_host|%>
                  <% if foreman_host.host_id? %>
                    <% if showSelectHostsNote %>
                      <p><%= _("Select the hosts to delete along with ") %> <%= app_instance %>: </p>
                      <% showSelectHostsNote = false %>
                    <% end %>
                      <%= check_box_tag 'foreman_host_ids[]', foreman_host.host_id, false, class: 'acd_host' -%> <%= h foreman_host.host.name -%>
                      </br>
                  <% end %>
                <% end %>
                <hr width="90%">
                <p> <%= check_box_tag "check_all", "", false, { :onchange => "toggleCheckboxesBySelector('.acd_host')" } %> Select / unselect all hosts</p>
                <br /><p><%= _("Note: Hosts which already existed and were added to the application instance are not shown in this dialog!") %></p> 
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-primary" data-dismiss="modal"><%= _('Cancel') %></button>
               <%= submit_tag _("Delete"), name: nil, class: "btn btn-danger" %>
               <% end %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

      <!-- Deploy Modal -->
      <div class="modal fade" id="deploy<%=app_instance.id%>" tabindex="-1" role="dialog" aria-labelledby="deployLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title"><%= _('Confirmation Box') %></h4>
            </div>
            <div class="modal-body">
              <p><%= _('Confirm to deploy ') %><%= app_instance%></p>
              <%= form_tag deploy_app_instance_path(:id => app_instance.id), :method => :post do %>
                <% if app_instance.foreman_hosts.where.not(:host_id => [nil, false]).any? %>
                  <ul>
                  <li><%= check_box_tag 'delete_hosts'-%> <%= _('Delete all hosts before deploying ') %><%= app_instance%></li>
                  <li><%= check_box_tag 'safe_deploy' -%> <%= _('Deploy only new and changed hosts for ') %><%= app_instance%></li>
                  </ul>
                <% end %>
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-danger" data-dismiss="modal"><%= _('Cancel') %></button>
               <%= submit_tag _("Submit"), name: nil, class: "btn btn-success" %>
               <% end %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
     </div><!-- /.modal -->
  <% end %>
</table>
<%= page_entries_info @app_instances %>
<%= will_paginate @app_instances %>

app/views/foreman_acd/app_instances/new.html.erb
<% title _('New Application Instance') %>

<% content_for(:javascripts) do %>
  <%= webpacked_plugins_js_for :foreman_acd %>
<% end %>

<%= render :partial => 'form' %>

app/views/foreman_acd/app_instances/report.html.erb
<% title _("Provisioning details for application instance #{@app_instance}") %>

<% content_for(:javascripts) do %>
  <%= webpacked_plugins_js_for :foreman_acd %>
<% end %>

<%
  json = {
    "deploymentState": @app_instance.deployment_state.to_s,
    "initialConfigureState": @app_instance.initial_configure_state.to_s,
    "appInstanceName": @app_instance.name,
    "hosts": @report_hosts,
    "deployTaskUrl": foreman_tasks_task_path(@app_instance.last_deploy_task),
    "configureJobUrl": job_invocations_path(search: "description ~ \"ACD application #{@app_instance.name}\""),
    "reportDataUrl": ui_acd_report_data_path("__id__"),
    "appInstanceId": @app_instance.id,
  }

  json["initialConfigureJobUrl"] = job_invocation_path(@app_instance.initial_configure_job) unless @app_instance.initial_configure_job.nil?
%>

<div id='report'></div>
  <%=  react_component('ApplicationInstanceReport', :data => json) %>
</div