config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope :acd, :path => '/acd' do
    resources :ansible_playbooks, :controller => 'foreman_acd/ansible_playbooks' do
      collection do
        get 'auto_complete_search'
        put 'sync_git_repo'
        post 'sync_git_repo'
      end

      member do
        post 'sync_git_repo'
        get 'import_vars'
      end
    end
    resources :app_definitions, :controller => 'foreman_acd/app_definitions' do
      collection do
        get 'auto_complete_search'
        get 'import'
        post 'handle_file_upload'
      end

      member do
        get 'export'
      end
    end

    resources :app_instances, :controller => 'foreman_acd/app_instances' do
      collection do
        get 'auto_complete_search'
      end

      member do
        post 'deploy'
        get 'report'
        delete 'destroy_with_hosts'
      end
    end

    match '/remote_execution', :controller => 'foreman_acd/remote_execution', :action => 'create', :via => [:post]

    get 'ui_acd_app/:id', :to => 'ui_acd#app', :constraints => { :id => /[\w.-]+/ }, :as => :ui_acd_app
    get 'ui_acd_foreman_data/:id', :to => 'ui_acd#foreman_data', :constraints => { :id => /[\w.-]+/ }, :as => :ui_acd_foreman_data
    get 'ui_acd_ansible_data/:id', :to => 'ui_acd#ansible_data', :constraints => { :id => /[\w.-]+/ }, :as => :ui_acd_ansible_data
    get 'ui_acd_report_data/:id', :to => 'ui_acd#report_data', :constraints => { :id => /[\w.-]+/ }, :as => :ui_acd_report_data
    get 'ui_acd_validate_hostname', :to => 'ui_acd#validate_hostname', :as => :ui_acd_validate_hostname

    scope :api, :path => '/api', :defaults => { :format => 'json' } do
      scope '(:apiv)', :defaults => { :apiv => 'v2' },
                       :apiv => /v1|v2/, :constraints => ApiConstraints.new(:version => 2) do
        constraints(:id => /[\w.-]+/) do
          resources :app_definitions, :only => [:show, :index], :controller => 'foreman_acd/api/v2/app_definitions', :as => :acd_api_v2_app_definitions
          resources :app_instances, :only => [:show, :index], :controller => 'foreman_acd/api/v2/app_instances', :as => :api_v2_foreman_acd_app_instances
          resources :ansible_playbooks, :only => [:show, :index], :controller => 'foreman_acd/api/v2/ansible_playbooks', :as => :api_v2_foreman_acd_ansible_playbooks do
            member do
              get 'grab'
            end
          end
        end
      end
    end
  end
end

app/models/foreman_acd/taxonomy_extensions.rb
# frozen_string_literal: true

module ForemanAcd
  # This is a TaxonomyExtensions
  module TaxonomyExtensions
    extend ActiveSupport::Concern

    included do
      if SETTINGS[:version].to_s.to_f <= 1.7
        def self.enabled_taxonomies
          %w[locations organizations].select { |taxonomy| SETTINGS["#{taxonomy}_enabled".to_sym] }
        end
      end
    end
  end
end
# To be removed after 1.7 compatibility is no longer required

app/controllers/foreman_acd/ansible_playbooks_controller.rb
# frozen_string_literal: true

module ForemanAcd
  # Ansible Playbook Controller
  class AnsiblePlaybooksController < ::ForemanAcd::ApplicationController
    include Foreman::Controller::AutoCompleteSearch
    include ::ForemanAcd::Concerns::AnsiblePlaybookParameters

    before_action :find_resource, :only => [:edit, :update, :destroy, :import_vars]
    after_action :delete_synced_repo, :only => [:new, :edit, :create, :update, :destroy, :index]

    def index
      @ansible_playbooks = resource_base.search_for(params[:search], :order => params[:order]).paginate(:page => params[:page])
    end

    def new
      @ansible_playbook = AnsiblePlaybook.new
    end

    def create
      @ansible_playbook = AnsiblePlaybook.new(ansible_playbook_params)
      if session[:git_path]
        @ansible_playbook.update(:path => ansible_playbook_full_path(ansible_playbook_rename(@ansible_playbook[:name])))
        FileUtils.mv(session[:git_path], @ansible_playbook[:path])
        session[:git_path] = nil
      end
      if @ansible_playbook.save
        process_success :success_msg => _("Successfully created %s. You need to press the \"Import groups\" button
                                           before this ansible playbook can be used in App Definitions!") % @ansible_playbook
      else
        process_error
      end
    end

    def edit
    end

    def update
      # Move synced repo to new path if ansible_playbook name is changed
      if !session[:git_path].nil? && ansible_playbook_params[:name] != @ansible_playbook[:name]
        FileUtils.mv(@ansible_playbook[:path], ansible_playbook_full_path(ansible_playbook_rename(ansible_playbook_params[:name])))
        @ansible_playbook.update(:path => ansible_playbook_full_path(ansible_playbook_rename(ansible_playbook_params[:name])))
        session[:git_path] = nil

      # Remove old version and copy new version of synced repository
      elsif !session[:git_path].nil? && ansible_playbook_params[:name] == @ansible_playbook.name
        remove_ansible_dir(@ansible_playbook[:path]) if @ansible_playbook.path
        @ansible_playbook.update(:path => ansible_playbook_full_path(ansible_playbook_rename(@ansible_playbook[:name])))
        FileUtils.mv(session[:git_path], @ansible_playbook[:path])
        session[:git_path] = nil
      end

      if @ansible_playbook.update(ansible_playbook_params)
        process_success
      else
        process_error
      end
    end

    def destroy
      if @ansible_playbook.destroy
        process_success
      else
        process_error
      end
    end

    def sync_git_repo
      @ansible_playbook = AnsiblePlaybook.new
      sync_params = params[:ansible_playbook]
      dir = Dir.mktmpdir

      begin
        git = Git.init(dir)

        if ForemanAcd.proxy_setting.present?
          git.config('http.proxy', ForemanAcd.proxy_setting)
          logger.info("HTTP Proxy used: #{git.config['http.proxy']}")
        end

        if sync_params[:git_commit].empty?
          if ForemanAcd.proxy_setting.present?
            err_msg = _('Please set the Git Branch/Tag/Commit. This setting is necessary if a HTTP proxy is used!')
            raise StandardError, err_msg
          else
            commit = Git.ls_remote(sync_params[:git_url])['head'][:sha]
          end
        else
          commit = sync_params[:git_commit]
        end

        git.add_remote('origin', sync_params[:git_url])
        git.fetch
        git.checkout(commit)

        session[:git_path] = git.dir.path
      rescue StandardError => e
        logger.error("Failed to sync git repository: #{e}")
        render :json => { :status => 'error', :message => e }, :status => :internal_server_error
      end
    end

    # Remove abandoned synced git repositories
    def delete_synced_repo
      names = []
      AnsiblePlaybook.all.each do |ansible_playbook|
        names.push(ansible_playbook_rename(ansible_playbook.name))
      end
      names.push('.', '..')
      return unless Dir.exist?(ForemanAcd.ansible_playbook_path)
      Dir.foreach(ForemanAcd.ansible_playbook_path) do |dirname|
        next if names.include? dirname
        remove_ansible_dir(ansible_playbook_full_path(dirname))
        logger.info("Successfully removed #{dirname}")
      end
    end

    def action_permission
      case params[:action]
      when 'import_vars'
        :import_vars
      when 'sync_git_repo'
        :sync_git_repo
      when 'grab'
        :grab
      else
        super
      end
    end

    # We need to move these to a smart_proxy_acd
    def extract_variables(playbook_path)
      errors = []
      vars = {}

      unless File.directory?(playbook_path) || File.directory?("#{playbook_path}/group_vars")
        errors << "Playbook path '#{playbook_path}' or '#{playbook_path}/group_vars' doesn't exist"
        return vars, errors
      end

      everything_empty = true

      vars_files = Dir.glob("#{playbook_path}/group_vars/**/*")
      vars_files.each do |vars_file|
        loaded_yaml = {}
        next if File.directory?(vars_file)

        begin
          loaded_yaml = YAML.load_file(vars_file)
        rescue Psych::SyntaxError
          err = "#{vars_file} is not YAML file"
          logger.error(err)
          errors << err
        end
        unless loaded_yaml.is_a? Hash
          err = "Could not parse YAML file #{vars_file}"
          logger.error(err)
          errors << err
        end
        everything_empty = false unless loaded_yaml.empty?

        # We need to support: group_vars/group_file and group_vars/group_dir/yaml_files
        dir_and_file = File.split(vars_file)

        group_name = if File.basename(dir_and_file[0]) == 'group_vars' # in case of group_vars/group_file
                       File.basename(dir_and_file[1], '.*')
                     else # in case of group_vars/group_dir/yaml_files
                       File.basename(dir_and_file[0])
                     end

        logger.debug("Add ansible vars from file #{vars_file} to group #{group_name}")

        if vars.key?(group_name)
          vars[group_name].merge!(loaded_yaml)
        else
          vars[group_name] = loaded_yaml
        end
      end

      errors << "No ansible group variable in #{playbook_path} defined." if everything_empty

      [vars, errors]
    end

    def import_vars
      logger.debug("Load ansible group vars for #{@ansible_playbook} from #{@ansible_playbook.path}")
      vars, errors = extract_variables(@ansible_playbook.path)
      @ansible_playbook.vars = vars.to_json
      @ansible_playbook.save
      if errors.empty?
        process_success :success_msg => _('Successfully loaded ansible group variables from %s') % @ansible_playbook.name, :redirect => ansible_playbooks_path
      else
        process_error :error_msg => _(errors.join(' ')), :redirect => ansible_playbooks_path
      end
    end

    private

    def ansible_playbook_rename(name)
      name.split(/\W+/).join('_')
    end

    def remove_ansible_dir(dirpath)
      unless dirpath.start_with? ForemanAcd.ansible_playbook_path
        logger.error("Sorry, the directory #{dirpath} is not within #{ForemanAcd.ansible_playbook_path} and will therefore not be cleaned up!")
        return false
      end
      FileUtils.rm_rf(dirpath) if Dir.exist?(dirpath)
    end

    def ansible_playbook_full_path(dirname)
      File.join(ForemanAcd.ansible_playbook_path, dirname)
    end
  end
end

app/controllers/foreman_acd/api/v2/ansible_playbooks_controller.rb
# frozen_string_literal: true

module ForemanAcd
  module Api
    module V2
      # API controller for Ansible Playbooks
      class AnsiblePlaybooksController < ::ForemanAcd::Api::V2::BaseController
        include ::Foreman::Controller::SmartProxyAuth
        include ::ForemanAcd::Concerns::AnsiblePlaybookParameters

        before_action :find_resource, :except => [:index, :create, :grab]

        add_smart_proxy_filters :grab, :features => 'ACD'

        api :GET, '/ansible_playbooks/:id', N_('Show ansible playbook')
        param :id, :identifier, :required => true
        def show
        end

        api :GET, '/ansible_playbooks', N_('List ansible playbooks')
        param_group :search_and_pagination, ::Api::V2::BaseController
        add_scoped_search_description_for(AnsiblePlaybook)
        def index
          @ansible_playbooks = resource_scope_for_index
        end

        def_param_group :ansible_playbook do
          param :ansible_playbook, Hash, :required => true, :action_aware => true do
            param :name, String, :required => true
            param_group :taxonomies, ::Api::V2::BaseController
            param :description, String, :required => true
            param :services, String, :required => true
          end
        end

        api :POST, '/ansible_playbooks', N_('Create a ansible playbook')
        param_group :ansible_playbook, :as => :create
        def create
          @ansible_playbook = AnsiblePlaybook.new(ansible_playbook_params)
          process_response @ansible_playbook.save
        end

        api :DELETE, '/ansible_playbooks/:id', N_('Deletes ansible playbook')
        param :id, :identifier, :required => true
        def destroy
          process_response @ansible_playbook.destroy
        end

        api :GET, '/ansible_playbooks/:id/grab', N_('Grab ansible playbook')
        param :id, :identifier, :required => true
        def grab
          ap = resource_class.find(params['id'])
          command = "tar cz -C #{ap.path} --exclude \".git\" . 2>/dev/null | base64"
          result = `#{command}`
          send_data result, :type => 'text/plain', :disposition => 'inline'
        end

        def action_permission
          case params[:action]
          when 'grab'
            'grab'
          else
            super
          end
        end

        def resource_class
          ForemanAcd::AnsiblePlaybook
        end
      end
    end
  end
end

app/controllers/foreman_acd/api/v2/app_definitions_controller.rb
# frozen_string_literal: true

module ForemanAcd
  module Api
    module V2
      # API controller for App Definitions
      class AppDefinitionsController < ::ForemanAcd::Api::V2::BaseController
        include ::ForemanAcd::Concerns::AppDefinitionParameters

        before_action :find_resource, :except => [:index, :create]

        api :GET, '/app_definitions/:id', N_('Show application definition')
        param :id, :identifier, :required => true
        def show
        end

        api :GET, '/app_definitions', N_('List application definitions')
        param_group :search_and_pagination, ::Api::V2::BaseController
        add_scoped_search_description_for(AppDefinition)
        def index
          @app_definitions = resource_scope_for_index
        end

        def_param_group :app_definition do
          param :app_definition, Hash, :required => true, :action_aware => true do
            param :name, String, :required => true
            param_group :taxonomies, ::Api::V2::BaseController
            param :description, String, :required => true
            param :services, String, :required => true
          end
        end

        api :POST, '/app_definitions', N_('Create a application definition')
        param_group :app_definition, :as => :create
        def create
          @app_definition = AppDefinition.new(app_definition_params)
          process_response @app_definition.save
        end

        api :DELETE, '/app_definitions/:id', N_('Deletes application definition')
        param :id, :identifier, :required => true
        def destroy
          process_response @app_definition.destroy
        end

        def controller_permission
          'app_definitions'
        end

        def resource_class
          ForemanAcd::AppDefinition
        end
      end
    end
  end
end

app/controllers/foreman_acd/api/v2/app_instances_controller.rb
# frozen_string_literal: true

module ForemanAcd
  module Api
    module V2
      # API controller for App Instances
      class AppInstancesController < ::ForemanAcd::Api::V2::BaseController
        include ::ForemanAcd::Concerns::AppInstanceParameters

        before_action :find_resource, :except => [:index, :create]

        api :GET, '/app_instances/:id', N_('Show application instance')
        param :id, :identifier, :required => true
        param :organization_id, :identifier, :required => true
        param :location_id, :identifier, :required => true
        def show
        end

        api :GET, '/app_instances', N_('List application instances')
        param :organization_id, :identifier, :required => true
        param :location_id, :identifier, :required => true
        param_group :search_and_pagination, ::Api::V2::BaseController
        add_scoped_search_description_for(AppInstance)
        def index
          scope = resource_scope_for_index.where(:organization => params[:organization_id]) if params[:organization_id].present?
          scope = scope.where(:location => params[:location_id]) if params[:location_id].present?
          @app_instances = scope
        end

        def_param_group :app_instance do
          param :app_instance, Hash, :required => true, :action_aware => true do
            param :name, String, :required => true
            param :organization_id, :identifier, :required => true
            param :location_id, :identifier, :required => true
            param :description, String, :required => true
            param :services, String, :required => true
          end
        end

        api :POST, '/app_instances', N_('Create a application instance')
        param_group :app_instance, :as => :create
        def create
          @app_instance = AppInstance.new(app_instance_params)
          process_response @app_instance.save
        end

        api :DELETE, '/app_instances/:id', N_('Deletes application instance')
        param :id, :identifier, :required => true
        def destroy
          process_response @app_instance.destroy
        end

        def controller_permission
          'app_instances'
        end

        def resource_class
          ForemanAcd::AppInstance
        end
      end
    end
  end
end

app/controllers/foreman_acd/api/v2/base_controller.rb
# frozen_string_literal: true

module ForemanAcd
  module Api
    module V2
      # Base Controller for all Acd API controllers
      class BaseController < ::Api::V2::BaseController
        resource_description do
          resource_id 'foreman_acd'
          api_version 'v2'
          api_base_url '/acd/api'
        end
      end
    end
  end
end

app/controllers/foreman_acd/application_controller.rb
# frozen_string_literal: true

module ForemanAcd
  # Base controller for all controllers
  class ApplicationController < ::ApplicationController
    def resource_class
      "ForemanAcd::#{controller_name.singularize.classify}".constantize
    end
  end
end

app/views/foreman_acd/app_definitions/_form.html.erb
<%
  json = {
    "organization": current_organization,
    "location": current_location,
    "hostgroups": @hostgroups,
    "foremanDataUrl": ui_acd_foreman_data_path("__id__"),
    "ansibleDataUrl": ui_acd_ansible_data_path("__id__"),
    "services": [],
    "ansibleVarsAll": [],
  }

  if @app_definition.new_record?
    json["mode"] = "newDefinition"
    json["ansiblePlaybooks"] = @ansible_playbooks
  else
    json["mode"] = "editDefinition"
    json["ansiblePlaybook"] = @app_definition.ansible_playbook.as_unified_structobj
  end

  if @app_definition.services.present?
    json["services"] = JSON.parse(@app_definition.services)
  end

  if @app_definition.ansible_vars_all.present?
    json["ansibleVarsAll"] = JSON.parse(@app_definition.ansible_vars_all)
  end

   json["supportedPlugins"] = {}
   json["supportedPlugins"]["puppet"] = defined?(ForemanPuppet) != nil
   json["supportedPlugins"]["katello"] = defined?(Katello) != nil
%>

<%= form_for @app_definition, :url => (@app_definition.new_record? ? app_definitions_path : app_definition_path(:id => @app_definition.id)) do |f| %>
  <%= base_errors_for @app_definition %>
  <ul class="nav nav-tabs" data-tabs="tabs">
    <li class="active"><a href="#primary" data-toggle="tab"><%= _('Application Definitions') %></a></li>
    <% if show_location_tab? %>
          <li><a href="#locations" data-toggle="tab"><%= _("Locations") %></a></li>
      <% end %>
      <% if show_organization_tab? %>
          <li><a href="#organizations" data-toggle="tab"><%= _("Organizations") %></a></li>
      <% end %>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="primary">
      <%= text_f f, :name %>
      <%= text_f f, :description %>

      <div id='app_definition'></div>
      <%=  react_component('ApplicationDefinition', :data => json) %>
    </div>

    <%= render 'taxonomies/loc_org_tabs', :f => f, :obj => @app_definition %>
  </div>

  <%= submit_or_cancel f %>
<% end %>

app/views/foreman_acd/app_definitions/edit.html.erb
<%=
  breadcrumbs(:resource_url => "/acd/api/v2/app_definitions",
              :items => [
                { :caption => _('App Definitions'),
                  :url => url_for(app_definitions_path) },
                { :caption => "Edit #{@app_definition.name}",
                  :url => (edit_app_definition_path(@app_definition) if authorized_for(hash_for_edit_app_definition_path(@app_definition))) }
              ])
%>

<% title(_('Edit Application Definition %s') % @app_definition) %>

<% content_for(:javascripts) do %>
  <%= webpacked_plugins_js_for :foreman_acd %>
<% end %>

<%= render :partial => 'form' %>

app/views/foreman_acd/app_definitions/import.html.erb
<%= javascript_include_tag *webpack_asset_paths('foreman_acd', extension: 'js') %>
<%
  json = {
    "organization": current_organization,
    "location": current_location,
    "hostgroups": @hostgroups,
    "foremanDataUrl": ui_acd_foreman_data_path("__id__"),
    "ansibleDataUrl": ui_acd_ansible_data_path("__id__"),
    "services": [],
    "ansibleVarsAll": [],
  }

  if @app_definition.new_record?
    json["mode"] = "newDefinition"
  else
    json["mode"] = "editDefinition"
  end
%>

<% title _('Import Application Definition') %>

<%= form_for @app_definition, :url => (app_definitions_path), :html => { :multipart => true } do |f| %>
  <%= base_errors_for @app_definition %>
  <ul class="nav nav-tabs" data-tabs="tabs">
    <li class="active"><a href="#primary" data-toggle="tab"><%= _('Application Definitions') %></a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="primary">
      <%= text_f f, :name %>
      <%= text_f f, :description %>
      <%= react_component('ApplicationDefinitionImport', json,)  %>
    </div>
  </div>

  <%= submit_or_cancel f %>
<% end %>

app/views/foreman_acd/app_definitions/index.html.erb
<% title _('Application Definitions') %>

<% title_actions new_link(_('New Application Definition')), display_link_if_authorized(_("Import"), hash_for_import_app_definitions_path, :class => 'btn btn-default')  %>

<table class="table table-bordered table-striped">
  <tr>
    <th><%= sort :name, :as => s_('AppDefinition|Name') %></th>
    <th><%= _('Description') %></th>
    <th><%= _('Actions') %></th>
  </tr>
  <% for app_definition in @app_definitions %>
    <tr>
      <td><%=link_to_if_authorized h(app_definition.name), hash_for_edit_app_definition_path(:id => app_definition) %></td>
      <td><%= app_definition.description %></td>
      <td>
        <%= action_buttons(
          display_delete_if_authorized(hash_for_app_definition_path(:id => app_definition),
                                       :data => { 'confirm': _('Delete %s?') % app_definition.name }),
          display_link_if_authorized(_("Export"), hash_for_export_app_definition_path(:id => app_definition))
        ) %>
      </td>
    </tr>
  <% end %>
</table>

<%= page_entries_info @app_definitions %>
<%= will_paginate @app_definitions %>

app/views/foreman_acd/app_definitions/new.html.erb
<% title _('New Application Definition') %>

<% content_for(:javascripts) do %>
  <%= webpacked_plugins_js_for :foreman_acd %>
<% end %>

<%= render :partial => 'form' %>